---
- include_tasks: repos.yml
  tags:
    - repos

- include_tasks: users.yml
  tags:
    - users

- include_tasks: packages.yml
  tags:
    - packages

- include_tasks: remote_archives.yml
  tags:
    - remote_archives

- include_tasks: pip.yml
  tags:
    - pip
