---
- name: Install packages
  dnf: 
    name: 
    - git
    - openssl
    - python2-pip
    - vim-enhanced
    state: latest

- name: Update
  dnf:
    name: '*'
    # bugfix is handled properly in ansible 2.7, but not in 2.4
    #bugfix: true
    state: latest

- pip:
    name: pip
    state: latest
