---
# tasks file for hopper
- name: virtualbox repo file
  template: 
    src: templates/virtualbox.repo.j2
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644

- name: vscode repo file
  template: 
    src: templates/vscode.repo.j2
    dest: /etc/yum.repos.d/vscode.repo
    owner: root
    group: root
    mode: 0644

- name: dnf update
  dnf:
    name: "*"
    state: latest

- name: group install Develoment tools
  dnf:
    name: 
      - '@Development Tools'
    state: latest

- name: packages
  dnf:
    name:
      - awscli
      - binutils
      - clang
      - cmake
      - code
      - compat-ffmpeg28
      - dkms
      - dnf-utils
      - device-mapper-persistent-data
      - facter
      - git
      - glibc-devel
      - glibc-headers
      - golang
      - jq
      - kernel-headers
      - kernel-devel 
      - libgomp
      - libselinux-python
      - libxkbcommon
      - lvm2
      - make
      - net-tools
      - openconnect
      - patch
      - python2-devel
      - python3-devel
      - qt5-qtx11extras
      - redhat-rpm-config
      - snapd
      - VirtualBox-5.2
      - vagrant
    state: latest

- name: check if /etc/yum.repos.d/docker-ce.repo
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repo

- name: download docker-ce repo
  get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  when: docker_ce_repo.stat.exists == false

- name: install docker-ce
  dnf:
    name: docker-ce
    state: latest
    
- name: pip install packages
  pip:
    name:
      - boto
      - boto3
      - molecule
      - six
        
- name: check if /usr/local/bin/terraform exists
  stat:
    path: /usr/local/bin/terraform
  register: terraform_executable

- name: download and unpack terraform zip archive
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
  when: terraform_executable.stat.exists == false

- name: "bashrc for {{ user }}"
  template:
    src: templates/bashrc.j2
    dest: ~{{user}}/.bashrc
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

# Not working - the regexp still isn't right
- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    #regexp: "#%wheel\s\ALL=(ALL)\sNOPASSWD:\sALL"
    regexp: "#%wheel  ALL="
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'
